s = set()
#print(type(s))
#s_from_list = set([1, 2, 3, 4])
#print(s_from_list)
#print(type(s_from_lis))
s.add(1)
s.add(2)
#s1 = s.union({1,2,3,4})
#s1 = s.intersection({1,2,3,4})
#print(s, s1)
print(len((s)))
s2 = {4,5}
#print(s.isdisjoint(s2))
s.add(8)
s.add(7)
s.remove(8)
